version: '3'

volumes:
    postgres_data: {}
    postgres_data_backups: {}

services:
    django:
        image: python:3.7-slim-buster
        container_name: restApi_django
        depends_on:
            - postgres
        volumes:
            - .:/app
            - ./static:/static
        working_dir: /app
        ports: 
            - 8000:8000
        command: bash -c "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn -w 4 -t 180 -b 0.0.0.0:8000 restApi.wsgi"
    postgres:
        image: postgres:12-alpine
        container_name: restApi_postgres
        environment:
            POSTGRES_USER: rest_geek2020
            POSTGRES_DB: rest_api
            POSTGRES_PASS: 8NrQ5xJ9neafbCKiqXtfEgPDQuWBrEpdV97aXvu6
            POSTGRES_PASSWORD: 8NrQ5xJ9neafbCKiqXtfEgPDQuWBrEpdV97aXvu6
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_data_backups:/backups
        ports:
            - 5432:5432
        env_file:
            - .env

    redis:
        image: redis:6-alpine
        container_name: restApi_redis