# Generated by Django 3.0.6 on 2020-05-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='foreman',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisitionmeta',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Requisition'),
        ),
    ]
